version: '3'

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.99.0/24

services:
  nginx:
    image: nginx-prof:latest
    container_name: nginx-prof
    build: 
      context: . 
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
      - "8081:8081" 
    networks:
      - internal
    depends_on:
      - php-fpm

  php-fpm:
    image: php-prof:fpm
    container_name: php-fpm-prof
    build: 
      context: . 
      dockerfile: php-fpm/Dockerfile
    networks:
      - internal

